### ISSUE TITLE
Windows issues?

### ISSUE THREAD

**Issue by kwilcox** [conda-forge/pynco-feedstock#2]
What are the issues preventing Windows builds? Anything I can work on?

**Comment by ocefpaf** [comment]
We need to build (or re-package a binary) for `nco` on Windows.

**Comment by rsignell-usgs** [comment]
Hopefully with the recent success of `antlr` builds on windows (https://github.com/antlr/antlr4/pull/1268),  `nco` builds on windows may be possible.

**Comment by ocefpaf** [comment]
> Hopefully with the recent success of `antlr` builds on windows (https://github.com/antlr/antlr4/pull/1268),  `nco` builds on windows may be possible. 

Not really. `nco` uses a small part of `antlr 2`. I do not believe it works with `antlr` 3 or 4. Still, that is not the bottleneck, as `antlr` is used only to compile `ncap2`. So we can still get a functional `nco` without it.

PS: we should move this conversation to https://github.com/conda-forge/nco-feedstock/issues/6

**Comment by ocefpaf** [comment]
I guess we can close this.
