### ISSUE TITLE
Problem running ncks from conda-forge pynco installation

### ISSUE THREAD

**Issue by mjbrodzik** [conda-forge/pynco-feedstock#7]
I am trying to debug a problem with a package I am deploying that uses the conda-forge pynco v0.0.3.  The error is complaining about libgsl.  I have removed all of my own package stuff and I believe I have created the problem using a fresh conda env and installing pynco and then running ncks with these commands:

```shell
conda create -n testpynco python=3.6
source activate testpynco
conda install pynco
ncks
```

```
The error message is:
(testpynco) vpn-nsidc227-dhcp:~ brodzik$ ncks
dyld: Library not loaded: @rpath/libgsl.19.dylib
  Referenced from: /Users/brodzik/.conda/envs/testpynco/bin/ncks
  Reason: Incompatible library version: ncks requires version 22.0.0 or later, but libgsl.19.dylib provides version 20.0.0
Abort trap: 6
(testpynco) vpn-nsidc227-dhcp:~ brodzik$
```

I checked the pynco dependencies, they don't include gsl.

Thanks for any help on sorting this out.

**Comment by ocefpaf** [comment]
> I checked the pynco dependencies, they don't include gsl.

`pynco` does not but `nco` does and `pynco` depends on that.

Can you send me the results of your `conda info`, `conda list` for that env and `cat ~/.condarc`?

**Comment by mjbrodzik** [comment]
Hi, thanks for fast response, yes, here is my conda info

(testpynco) vpn-nsidc227-dhcp:~ brodzik$ conda info
Current conda install:

               platform : osx-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : not installed
         python version : 2.7.12.final.0
       requests version : 2.18.1
       root environment : /opt/miniconda  (read only)
    default environment : /Users/brodzik/.conda/envs/testpynco
       envs directories : /Users/brodzik/.conda/envs
                          /opt/miniconda/envs
          package cache : /opt/miniconda/pkgs
                          /Users/brodzik/.conda/pkgs
           channel URLs : https://conda.anaconda.org/nsidc/channel/main/osx-64
                          https://conda.anaconda.org/nsidc/channel/main/noarch
                          https://conda.anaconda.org/nsidc/channel/dev/osx-64
                          https://conda.anaconda.org/nsidc/channel/dev/noarch
                          https://conda.anaconda.org/conda-forge/channel/main/osx-64
                          https://conda.anaconda.org/conda-forge/channel/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/brodzik/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.22 requests/2.18.1 CPython/2.7.12 Darwin/16.7.0 OSX/10.12.6    
                UID:GID : 13159:200
(testpynco) vpn-nsidc227-dhcp:~ brodzik$

**Comment by mjbrodzik** [comment]
and my conda list:

```
(testpynco) vpn-nsidc227-dhcp:~ brodzik$ conda list
# packages in environment at /Users/brodzik/.conda/envs/testpynco:
#
ca-certificates           2017.7.27.1                   0    conda-forge/channel/main
certifi                   2017.7.27.1              py36_0    conda-forge/channel/main
curl                      7.54.1                        0    conda-forge/channel/main
esmf                      7.0.0                         6    conda-forge/channel/main
expat                     2.2.1                         0    conda-forge/channel/main
gsl                       2.1                           2    conda-forge/channel/main
h5py                      2.7.1                    py36_1    conda-forge/channel/main
hdf4                      4.2.12                        0    conda-forge/channel/main
hdf5                      1.8.18                        0    conda-forge/channel/main
jpeg                      9b                            1    conda-forge/channel/main
krb5                      1.14.2                        0    conda-forge/channel/main
libgcc                    4.8.5                         1    defaults
libgfortran               3.0.0                         0    conda-forge/channel/main
libnetcdf                 4.4.1.1                       5    conda-forge/channel/main
libssh2                   1.8.0                         1    conda-forge/channel/main
mkl                       2017.0.3                      0    defaults
mpich                     3.2                           5    conda-forge/channel/main
nco                       4.6.9                         0    conda-forge/channel/main
ncurses                   5.9                          10    conda-forge/channel/main
netcdf-fortran            4.4.4                         3    conda-forge/channel/main
netcdf4                   1.3.0                    py36_0    conda-forge/channel/main
numpy                     1.13.1                   py36_0    defaults
openblas                  0.2.19                        2    conda-forge/channel/main
openssl                   1.0.2l                        0    conda-forge/channel/main
pip                       9.0.1                    py36_0    conda-forge/channel/main
pynco                     0.0.3                    py36_0    conda-forge/channel/main
python                    3.6.2                         0    conda-forge/channel/main
python-dateutil           2.6.1                    py36_0    conda-forge/channel/main
readline                  6.2                           0    conda-forge/channel/main
scipy                     0.19.1              np113py36_0    defaults
setuptools                36.3.0                   py36_0    conda-forge/channel/main
six                       1.11.0                   py36_1    conda-forge/channel/main
sqlite                    3.13.0                        1    conda-forge/channel/main
tk                        8.5.19                        2    conda-forge/channel/main
udunits2                  2.2.23                        1    conda-forge/channel/main
wheel                     0.30.0                     py_1    conda-forge/channel/main
xz                        5.2.3                         0    conda-forge/channel/main
zlib                      1.2.11                        0    conda-forge/channel/main
(testpynco) vpn-nsidc227-dhcp:~ brodzik$ 
```

**Comment by mjbrodzik** [comment]
and my .condarc:

```
(testpynco) vpn-nsidc227-dhcp:~ brodzik$ more ~/.condarc
channels:
  - https://conda.anaconda.org/nsidc/channel/main
  - https://conda.anaconda.org/nsidc/channel/dev
  - https://conda.anaconda.org/conda-forge/channel/main
  - defaults
always_yes: 'True'
show_channel_urls: 'True'
(testpynco) vpn-nsidc227-dhcp:~ brodzik$ 
```

**Comment by mjbrodzik** [comment]
(is there some way to do better block quotes in github markdown?)

**Comment by ocefpaf** [comment]
You are using 3 channels and two are on top of conda-forge, that may be the source of the issue.
However, I do not see any package from those channels installed in the env :-/

Note that `gsl` was installed, 6th line on your `conda list` result, but that is not the right version.
I'll try to inspect the package and see why that happened, meanwhile can you try force `conda install gsl=2.2.1` there and see if it fixes the issue?

**Comment by ocefpaf** [comment]
> (is there some way to do better block quotes in github markdown?)

I usually use gist links to for large outputs, or even attached files.

**Comment by mjbrodzik** [comment]
Yes, the extra channels are for the packages we deploy from NSIDC--Nothing's installed from there for this example because I was trying to isolate the issue.  

In the testgdal env, if I do:

conda install gsl=2.2

it installed gsl and also upgraded scipy and numpy to [blas-openblas]:

```
gsl:   2.1-2              conda-forge/channel/main --> 2.2.1-blas_openblas_2         conda-for\
ge/channel/main [blas_openblas]                                                                    
    numpy: 1.13.1-py36_0      defaults                 --> 1.13.1-py36_blas_openblas_200 conda-for\
ge/channel/main [blas_openblas]                                                                    
    scipy: 0.19.1-np113py36_0 defaults                 --> 0.19.1-py36_blas_openblas_202 conda-for\
ge/channel/main [blas_openblas] 
```


after that I was able to run ncks without the error.

**Comment by ocefpaf** [comment]
> after that I was able to run ncks without the error.

Cool! I'll close this and https://github.com/conda-forge/nco-feedstock/pull/44 should fix it for good.

Thanks for the report!

**Comment by mjbrodzik** [comment]
Felipe,  I have one more question, I'm a little new to conda packaging. 
How will I be able to tell when your pull request makes it into nco?

MJ

On Thu, 28 Sep 2017, Filipe wrote:

> Date: Thu, 28 Sep 2017 12:34:43 -0700
> From: Filipe <notifications@github.com>
> Reply-To: conda-forge/pynco-feedstock
>     <reply+004c8ae82dc7075c189c16614aa3df6cf10d61f6c0e30a7a92cf0000000115e510d
>     392a169ce0f94d29d@reply.github.com>
> To: conda-forge/pynco-feedstock <pynco-feedstock@noreply.github.com>
> Cc: Mary Jo Brodzik <brodzik@nsidc.org>, Author <author@noreply.github.com>
> Subject: Re: [conda-forge/pynco-feedstock] Problem running ncks from
>     conda-forge pynco installation (#7)
> 
>
>       after that I was able to run ncks without the error.
> 
> Cool! I'll close this and conda-forge/nco-feedstock#44 should fix it for
> good.
> 
> Thanks for the report!
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the
> thread.[AEyK6O7ePZYIHODOhRgl-qBU4LIlqytkks5sm_TTgaJpZM4Pnq-1.gif]
> 
> 
>

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mary Jo Brodzik, Senior Associate Scientist, 303-492-8263
NSIDC/CIRES, Univ. of Colo. at Boulder, 449 UCB, Boulder, CO 80309-0449
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
"We cannot solve our problems with the same thinking we used
when we created them."  --Albert Einstein

**Comment by mjbrodzik** [comment]
And in my package, will it mean I have to pin gsl?  or nco? or pynco? in my package?  Right now I just have pynco pinned to <=0.0.3,<0.1.0, but I don't know whether this the correct way to do this.

**Comment by ocefpaf** [comment]
You can 'watch' the repo to know when the PR is merged and then click on the CIs build job for the platform you are interested.

It should be up latet today or early tomorrow though.

**Comment by mjbrodzik** [comment]
Thanks and I see you just merged it.  I really appreciate your help and 
willingness to explain.

Mary Jo

On Thu, 28 Sep 2017, Filipe wrote:

> Date: Thu, 28 Sep 2017 20:26:51 +0000 (UTC)
> From: Filipe <notifications@github.com>
> Reply-To: conda-forge/pynco-feedstock
>     <reply+004c8ae84d01b815f9f1b2ae3b602a787588d722d23860ed92cf0000000115e51d0
>     b92a169ce0f94d29d@reply.github.com>
> To: conda-forge/pynco-feedstock <pynco-feedstock@noreply.github.com>
> Cc: Mary Jo Brodzik <brodzik@nsidc.org>, Author <author@noreply.github.com>
> Subject: Re: [conda-forge/pynco-feedstock] Problem running ncks from
>     conda-forge pynco installation (#7)
> 
> 
> You can 'watch' the repo to know when the PR is merged and then click on the
> CIs build job for the platform you are interested.
> 
> It should be up latet today or early tomorrow though.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the
> thread.[AEyK6KJm0mVvSH7jmYvyCHivEzS4_C3Hks5snAELgaJpZM4Pnq-1.gif]
> 
> 
>

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mary Jo Brodzik, Senior Associate Scientist, 303-492-8263
NSIDC/CIRES, Univ. of Colo. at Boulder, 449 UCB, Boulder, CO 80309-0449
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
"We cannot solve our problems with the same thinking we used
when we created them."  --Albert Einstein

**Comment by ocefpaf** [comment]
>Thanks and I see you just merged it.  I really appreciate your help and
willingness to explain.

No problem. As soon as https://travis-ci.org/conda-forge/nco-feedstock/builds/281040065 finishes the OS X package will be available. (The Linux package is already in the channel.)
